# 简介

Java异常是一个描述在代码段中发生的异常（也就是出错）情况的对象。当异常情况发生，一个代表该异常的对象被创建并且在导致该错误的方法中被抛出（throw）。该方法可以选择自己处理异常或传递该异常。
1. 该异常被捕获（caught）并处理。异常可能是由Java运行时系统产生，或者是由你的手工代码产生。
2. 被Java抛出的异常与违反语言规范或超出Java执行环境限制的基本错误有关。手工编码产生的异常基本上用于报告方法调用程序的出错状况。

Java异常处理通过5个关键字控制：try、catch、throw、throws和 finally。下面讲述它们如何工作的。程序声明了你想要的异常监控包含在一个try块中。如果在try块中发生异常，它被抛出。你的代码可以捕捉这个异常（用catch）并且用某种合理的方法处理该异常。系统产生的异常被Java运行时系统自动抛出。手动抛出一个异常，用关键字throw。任何被抛出方法的异常都必须通过throws子句定义。任何在方法返回前绝对被执行的代码被放置在finally块中。

下面是一个异常处理块的通常形式：
try {
  // block of code to monitor for errors
}
catch (ExceptionType1 exOb) {
  // exception handler for ExceptionType1
}
catch (ExceptionType2 exOb) {
  // exception handler for ExceptionType2
}
// ...
finally {
  // block of code to be executed before try block ends
}
这里，ExceptionType 是发生异常的类型。下面将介绍怎样应用这个框架。

# 异常类型
```
Throwable
	Exception
		RuntimeException
	Error
```
所有异常类型都是内置类Throwable的子类,紧接着Throwable下面的是两个把异常分成两个不同分支的子类。

## Exception
该类用于用户程序可能捕捉的异常情况。它也是你可以用来创建你自己用户异常类型子类的类。在Exception分支中有一个重要子类RuntimeException。该类型的异常自动为你所编写的程序定义并且包括被零除和非法数组索引这样的错误。

## Error
Error作为顶层，Error定义了在通常环境下不希望被程序捕获的异常。Error类型的异常用于Java运行时系统来显示与运行时系统本身有关的错误。堆栈溢出是这种错误的一例。因为它们通常是灾难性的致命错误，不是程序可以控制的。

# Java的内置异常

在标准包java.lang中，Java定义了若干个异常类。

这些异常一般是标准类RuntimeException的子类。因为java.lang实际上被所有的Java程序引入，多数从RuntimeException派生的异常都自动可用。而且，它们不需要被包含在任何方法的throws列表中。Java语言中，这被叫做未经检查的异常（unchecked exceptions ）。因为编译器不检查它来看一个方法是否处理或抛出了这些异常。 java.lang中定义的未经检查的异常列于表1。表2列出了由 java.lang定义的必须在方法的throws列表中包括的异常，如果这些方法能产生其中的某个异常但是不能自己处理它。这些叫做受检查的异常（checked exceptions）。Java定义了几种与不同类库相关的其他的异常类型。

表1：未检查异常

| 异常                           | 说明                               |
| ------------------------------ | ---------------------------------- |
| ArithmeticException            | 算术错误，如被0除                  |
| ArrayIndexOutOfBoundsException | 数组下标出界                       |
| ArrayStoreException            | 数组元素赋值类型不兼容             |
| ClassCastException             | 非法强制转换类型                   |
| IllegalArgumentException       | 调用方法的参数非法                 |
| IllegalMonitorStateException   | 非法监控操作，如等待一个未锁定线程 |
| IllegalStateException          | 环境或应用状态不正确               |
| IllegalThreadStateException    | 请求操作与当前线程状态不兼容       |
| IndexOutOfBoundsException      | 某些类型索引越界                   |
| NullPointerException           | 非法使用空引用                     |
| NumberFormatException          | 字符串到数字格式非法转换           |
| SecurityException              | 试图违反安全性                     |
| StringIndexOutOfBounds         | 试图在字符串边界之外索引           |
| UnsupportedOperationException  | 遇到不支持的操作                   |

表2：受检查异常

| 异常                       | 意义                                    |
| -------------------------- | --------------------------------------- |
| ClassNotFoundException     | 找不到类                                |
| CloneNotSupportedException | 试图克隆一个不能实现Cloneable接口的对象 |
| IllegalAccessException     | 对一个类的访问被拒绝                    |
| InstantiationException     | 试图创建一个抽象类或者抽象接口的对象    |
| InterruptedException       | 一个线程被另一个线程中断                |
| NoSuchFieldException       | 请求的字段不存在                        |
| NoSuchMethodException      | 请求的方法不存在                        |

# 自定义异常

尽管Java的内置异常处理大多数常见错误，你也许希望建立你自己的异常类型来处理你所应用的特殊情况。这是非常简单的：只要定义Exception的一个子类就可以了（Exception当然是Throwable的一个子类）。你的子类不需要实际执行什么——它们在类型系统中的存在允许你把它们当成异常使用。

Exception类自己没有定义任何方法。当然，它继承了Throwable提供的一些方法。因此，所有异常，包括你创建的，都可以获得Throwable定义的方法。这些方法显示在表10-3中。你还可以在你创建的异常类中覆盖一个或多个这样的方法。



| 方法                                    | 描述                                                         |
| --------------------------------------- | ------------------------------------------------------------ |
| Throwable fillInStackTrace( )           | 返回一个包含完整堆栈轨迹的Throwable对象，该对象可能被再次引发。 |
| String getLocalizedMessage( )           | 返回一个异常的局部描述                                       |
| String getMessage( )                    | 返回一个异常的描述                                           |
| void printStackTrace( )                 | 显示堆栈轨迹                                                 |
| void printStackTrace(PrintStreamstream) | 把堆栈轨迹送到指定的流                                       |
| void printStackTrace(PrintWriterstream) | 把堆栈轨迹送到指定的流                                       |
| String toString( )                      | 返回一个包含异常描述的String对象。当输出一个Throwable对象时，该方法被println( )调用 |