# 异常处理

Golang 没有结构化异常，使用 panic 抛出错误，recover 捕获错误。

Go中可以抛出一个panic的异常，然后在defer中通过recover捕获这个异常，然后正常处理。

## panic

```makefile
1、内置函数
2、假如函数F中书写了panic语句，会终止其后要执行的代码，在panic所在函数F内如果存在要执行的defer函数列表，按照defer的逆序执行
3、返回函数F的调用者G，在G中，调用函数F语句之后的代码不会执行，假如函数G中存在要执行的defer函数列表，按照defer的逆序执行
4、直到goroutine整个退出，并报告错误
```

## recover

```
1、内置函数
2、用来控制一个goroutine的panicking行为，捕获panic，从而影响应用的行为
3、一般的调用建议
    a). 在defer函数中，通过recever来终止一个goroutine的panicking过程，从而恢复正常代码的执行
    b). 可以获取通过panic传递的error
```

注意

```
1.利用recover处理panic指令，defer 必须放在 panic 之前定义，另外 recover 只有在 defer 调用的函数中才有效。否则当panic时，recover无法捕获到panic，无法防止panic扩散。
2.recover 处理异常后，逻辑并不会恢复到 panic 那个点去，函数跑到 defer 之后的那个点。
3.多个 defer 会形成 defer 栈，后定义的 defer 语句会被最先调用。
```

## 原型

```go
func panic(v interface{})
func recover() interface{}
//由于 panic、recover 参数类型为 interface{}，因此可抛出任何类型对象。
```

## 注意问题

- 延迟调用中引发的错误，可被后续延迟调用捕获，但仅最后一个错误可被捕获。

  ```go
  func test() {
      defer func() {
          fmt.Println(recover())
      }()
  
      defer func() {
          panic("defer panic")
      }()
  
      panic("test panic")
  }
  
  func main() {
      test()
  }
  //输出
      defer panic
  ```

  

- 捕获函数 recover 只有在延迟调用内直接调用才会终止错误，否则总是返回 nil。任何未捕获的错误都会沿调用堆栈向外传递。

```go
func test() {
    defer func() {
        fmt.Println(recover()) //有效
    }()
    defer recover()              //无效！
    defer fmt.Println(recover()) //无效！
    defer func() {
        func() {
            println("defer inner")
            recover() //无效！
        }()
    }()

    panic("test panic")
}

func main() {
    test()
}
//输出
defer inner
<nil>
test panic
```

- 使用延迟匿名函数或下面这样都是有效的。

```go
func except() {
    fmt.Println(recover())
}

func test() {
    defer except()
    panic("test panic")
}

func main() {
    test()
}
//输出
   test panic
```

- 如果需要保护代码 段，可将代码块重构成匿名函数，如此可确保后续代码被执 。

  ```go
  
  func test(x, y int) {
      var z int
  
      func() {
          defer func() {
              if recover() != nil {
                  z = 0
              }
          }()
          panic("test panic")
          z = x / y
          return
      }()
  
      fmt.Printf("x / y = %d\n", z)
  }
  
  func main() {
      test(2, 1)
  }
  //输出
      x / y = 0
  ```

  # error 方式错误

  除用 panic 引发中断性错误外，还可返回 error 类型错误对象来表示函数调用状态。

```go
type error interface {
    Error() string
}
```

标准库 errors.New 和 fmt.Errorf 函数用于创建实现 error 接口的错误对象。通过判断错误对象实例来确定具体错误类型。

```go
import (
    "errors"
    "fmt"
)

var ErrDivByZero = errors.New("division by zero")

func div(x, y int) (int, error) {
    if y == 0 {
        return 0, ErrDivByZero
    }
    return x / y, nil
}

func main() {
    defer func() {
        fmt.Println(recover())
    }()
    switch z, err := div(10, 0); err {
    case nil:
        println(z)
    case ErrDivByZero:
        panic(err)
    }
}
//输出
    division by zero
```

## Go实现类似 try catch 的异常处理

```go
func Try(fun func(), handler func(interface{})) {
    defer func() {
        if err := recover(); err != nil {
            handler(err)
        }
    }()
    fun()
}

func main() {
    Try(func() {
        panic("test panic")
    }, func(err interface{}) {
        fmt.Println(err)
    })
}
//输出
    test panic
```

如何区别使用 panic 和 error 两种方式?

惯例是:导致关键流程出现不可修复性错误的使用 panic，其他使用 error。



## 自定义error

```go
import (
    "fmt"
    "os"
    "time"
)

//定义一个错误结构体
type PathError struct {
    path       string
    op         string
    createTime string
    message    string
}

//错误方法
func (p *PathError) Error() string {
    return fmt.Sprintf("path=%s \nop=%s \ncreateTime=%s \nmessage=%s", p.path,
        p.op, p.createTime, p.message)
}

func Open(filename string) error {

    file, err := os.Open(filename)
    if err != nil {
        //返回错误结构体指针
        return &PathError{
            path:       filename,
            op:         "read",
            message:    err.Error(),
            createTime: fmt.Sprintf("%v", time.Now()),
        }
    }

    defer file.Close()
    return nil
}

func main() {
    err := Open("/Users/5lmh/Desktop/go/src/test.txt")
    switch v := err.(type) {
    case *PathError:
        fmt.Println("get path error,", v)
    default:

    }

}
//输出
get path error, path=/Users/pprof/Desktop/go/src/test.txt 
op=read 
createTime=2018-04-05 11:25:17.331915 +0800 CST m=+0.000441790 
message=open /Users/pprof/Desktop/go/src/test.txt: no such file or directory
```

